#!/usr/bin/env python3
"""
Generate MythicMobs YAML configs for every modogs bbmodel variant.

Reads bbmodel filenames from the dogs output dir, infers the breed,
applies size-tier stats, and writes one entry per variant to a single
YAML file (or split per-breed file if --split is passed).

Usage:
    python generate_mm_configs.py <bbmodels_dir> <output_yaml>
"""

import sys
from pathlib import Path

# Size tiers: HP / damage / movement_speed / scale_hint
SIZE_TIERS = {
    "small":  {"hp": 10.0, "dmg": 4.0, "speed": 0.32},
    "medium": {"hp": 16.0, "dmg": 6.0, "speed": 0.30},
    "large":  {"hp": 26.0, "dmg": 9.0, "speed": 0.26},
}

BREED_TIERS = {
    # Small breeds
    "beagle": "small", "basenji": "small", "boston_terrier": "small",
    "bull_terrier": "small", "cocker_spaniel": "small", "dachshund": "small",
    "ck_charles_spaniel": "small", "italian_greyhound": "small",
    "mini_pinscher": "small", "pug": "small", "russell_terrier": "small",
    "scottish_terrier": "small", "shiba_inu": "small", "whippet": "small",
    # Medium breeds
    "airedale_terrier": "medium", "australian_shepherd": "medium",
    "american_foxhound": "medium", "bloodhound": "medium",
    "border_collie": "medium", "boxer": "medium", "bulldog": "medium",
    "cardigan_corgi": "medium", "collie": "medium", "dalmatian": "medium",
    "doberman": "medium", "german_shepherd": "medium",
    "german_spitz": "medium", "golden_retriever": "medium",
    "greyhound": "medium", "husky": "medium", "irish_setter": "medium",
    "lab_retriever": "medium", "mudi": "medium",
    "norwegian_elkhound": "medium", "pembroke_corgi": "medium",
    "pit_bull": "medium", "poodle": "medium",
    "redbone_coonhound": "medium", "rottweiler": "medium",
    "schnauzer": "medium", "shetland_sheepdog": "medium",
    "tree_walk_hound": "medium",
    # Large breeds
    "alaskan_malamute": "large", "bernese_mountain_dog": "large",
    "great_dane": "large", "mastiff": "large", "saint_bernard": "large",
}

# Bbmodel filenames that are accessories, not real mobs
NON_MOB_BBMODELS = {"barrel", "target"}


def detect_breed(bbmodel_name: str) -> str | None:
    """Return the breed key for a bbmodel filename, or None if it's an accessory."""
    if bbmodel_name in NON_MOB_BBMODELS:
        return None
    # Try longest-prefix match against known breeds
    for breed in sorted(BREED_TIERS.keys(), key=len, reverse=True):
        if bbmodel_name == breed or bbmodel_name.startswith(breed + "_"):
            return breed
    return None


def pretty_breed(breed: str) -> str:
    return " ".join(w.capitalize() for w in breed.split("_"))


def pretty_variant_suffix(bbmodel_name: str, breed: str) -> str:
    """Extract and prettify the variant suffix (e.g. 'beagle_black_tan' -> 'Black Tan')."""
    if bbmodel_name == breed:
        return ""
    suffix = bbmodel_name[len(breed) + 1:]
    return " ".join(w.capitalize() for w in suffix.split("_"))


def mm_id(bbmodel_name: str) -> str:
    """MythicMobs internal id: PascalCase, prefixed Dog."""
    parts = bbmodel_name.split("_")
    return "Dog" + "".join(p.capitalize() for p in parts)


def main():
    if len(sys.argv) < 3:
        print("Usage: python generate_mm_configs.py <bbmodels_dir> <output_yaml>")
        sys.exit(1)

    bbmodels_dir = Path(sys.argv[1])
    output_yaml = Path(sys.argv[2])

    bbmodel_files = sorted(bbmodels_dir.glob("*.bbmodel"))
    if not bbmodel_files:
        print(f"No bbmodels found in {bbmodels_dir}")
        sys.exit(1)

    output_yaml.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    skipped = 0

    for bb in bbmodel_files:
        name = bb.stem
        breed = detect_breed(name)
        if breed is None:
            skipped += 1
            continue
        tier = SIZE_TIERS[BREED_TIERS[breed]]
        variant_suffix = pretty_variant_suffix(name, breed)
        display = f"&f{pretty_breed(breed)}"
        if variant_suffix:
            display += f" &7({variant_suffix})"

        entries.append({
            "id": mm_id(name),
            "model": name,
            "display": display,
            "breed": breed,
            "tier": BREED_TIERS[breed],
            "hp": tier["hp"],
            "dmg": tier["dmg"],
            "speed": tier["speed"],
        })

    # Write YAML
    lines = [
        "# ============================================================",
        "# Modogs - MythicMobs configs for FluffyMode",
        "# Auto-generated by tools/convert_modogs/generate_mm_configs.py",
        "# ============================================================",
        "# Original mod: modogs by Mod-O-Gs team (1.20.1 Forge)",
        "# Converted to ModelEngine + MythicMobs with permission.",
        "# Credit shown in ChaosCraft title screen.",
        "#",
        "# Each dog is a WOLF entity hosting a ModelEngine model. Vanilla AI",
        "# is cleared - FluffyMobAI (custom Java AI) handles all behaviour.",
        "# Spawned mobs are tagged 'fluffy:managed' and 'fluffy:type:dog' so",
        "# the Java AI picks them up automatically.",
        "# ============================================================",
        "",
    ]

    for e in entries:
        lines.extend([
            f"{e['id']}:",
            f"  Type: WOLF",
            f"  Display: '{e['display']}'",
            f"  Health: {e['hp']}",
            f"  Damage: {e['dmg']}",
            f"  Faction: fluffy",
            f"  AIGoalSelectors:",
            f"  - clear",
            f"  - 0 float",
            f"  AITargetSelectors:",
            f"  - clear",
            f"  Modules:",
            f"    ModelEngine:",
            f"      ModelID: {e['model']}",
            f"  Options:",
            f"    MovementSpeed: {e['speed']}",
            f"    PreventOtherDrops: true",
            f"    PreventSunburn: true",
            f"    Silent: true",
            f"    Despawn: true",
            f"    NoAI: false",
            f"    Collidable: true",
            f"    Persistent: false",
            f"  Tags:",
            f"  - fluffy:managed",
            f"  - fluffy:type:dog",
            f"  - fluffy:breed:{e['breed']}",
            f"  - fluffy:tier:{e['tier']}",
            "",
        ])

    output_yaml.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(entries)} mob entries to {output_yaml}")
    print(f"  Small:  {sum(1 for e in entries if e['tier'] == 'small')}")
    print(f"  Medium: {sum(1 for e in entries if e['tier'] == 'medium')}")
    print(f"  Large:  {sum(1 for e in entries if e['tier'] == 'large')}")
    if skipped:
        print(f"  Skipped {skipped} non-mob bbmodels (barrel, target)")


if __name__ == "__main__":
    main()
