package com.blockforge.chaoscraft.modes.calamity.attacks.phase4.environmental;

import com.blockforge.chaoscraft.ChaosCraftPlugin;
import com.blockforge.chaoscraft.modes.calamity.attacks.*;
import com.blockforge.chaoscraft.modes.calamity.display.DisplayBuilder;
import com.blockforge.chaoscraft.modes.calamity.display.DisplayBuilder.BlockDisplayHandle;
import org.bukkit.*;
import org.bukkit.entity.BlockDisplay;
import org.bukkit.entity.Player;
import org.bukkit.util.Transformation;
import org.bukkit.util.Vector;
import org.joml.AxisAngle4f;
import org.joml.Vector3f;

import java.util.ArrayList;
import java.util.List;

/**
 * Phase 4D Environmental -- GROUP 8: BOSS ESSENCE ECHO EVENTS
 * 10 attacks (#71-80) generated by the Dragon's movement and absorbed energy.
 * The Dragon's flight path leaves persistent damage marks on the arena.
 *
 * Design notes:
 * - No status effects
 * - Void Emperor palette: magenta (180,0,200), cyan (0,200,255), crimson (200,0,50), purple (128,0,255)
 * - Echo trails persist and accumulate -- arena becomes gridded with hazards
 * - Late fight -- damage range 8.0-18.0 HP
 */
public final class EssenceEcho {

    private EssenceEcho() {}

    public static void registerAll(ChaosCraftPlugin plugin, AttackRegistry registry) {
        registry.register(new FlameEchoTrail(plugin));
        registry.register(new VoidEchoTrail(plugin));
        registry.register(new CrystalEchoScatter(plugin));
        registry.register(new BrimstoneFootprint(plugin));
        registry.register(new OrbitTrailDensity(plugin));
        registry.register(new DivePathScar(plugin));
        registry.register(new CrystalResonanceField(plugin));
        registry.register(new DeepVoidAccumulation(plugin));
        registry.register(new WingDowndraftZone(plugin));
        registry.register(new FullEchoSaturation(plugin));
    }

    // =========================================================================
    // 71. PILLAR COLLAPSE WAVE -- crystal pillars collapse in rotating sequence
    // (Design doc #71 -- Pillar Collapse Wave)
    // =========================================================================
    public static class FlameEchoTrail extends EnvironmentalAttack {

        private final List<Location> trailZones = new ArrayList<>();
        private Location trailStart;
        private double trailAngle;

        public FlameEchoTrail(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("flame_echo_trail", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(220); // 11 seconds
            config.setCooldownTicks(300); // Triggers after firebreath
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            trailStart = center.clone();
            trailAngle = Math.random() * 2 * Math.PI;

            DisplayBuilder.playSound(center, Sound.ENTITY_BLAZE_SHOOT, 0.2f, 0.8f);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || trailStart == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Trail formation: first 60 ticks (3 seconds) -- placing zones along path
            if (ticksAlive <= 60 && ticksAlive % 3 == 0) {
                // Dragon's simulated flight path
                double pathProgress = ticksAlive / 60.0;
                double pathDist = pathProgress * 25;
                Location zonePos = trailStart.clone().add(
                        Math.cos(trailAngle) * pathDist,
                        3 + Math.sin(pathProgress * Math.PI) * 5, // Arc upward
                        Math.sin(trailAngle) * pathDist
                );
                trailZones.add(zonePos);

                // FLAME particles at zone
                w.spawnParticle(Particle.FLAME, zonePos, 5, 0.3, 0.3, 0.3, 0.02);
                DisplayBuilder.playSound(zonePos, Sound.ENTITY_BLAZE_SHOOT, 0.15f, 0.8f);
            }

            // Active zones: FLAME particles + damage for 8 seconds (160 ticks)
            if (ticksAlive > 10) {
                // Particle maintenance
                if (ticksAlive % 6 == 0) {
                    for (Location zone : trailZones) {
                        w.spawnParticle(Particle.FLAME, zone, 3, 0.5, 0.5, 0.5, 0.01);
                    }
                }

                // Damage: 3 fire per second per zone
                if (ticksAlive % 20 == 0) {
                    for (Location zone : trailZones) {
                        for (Player p : w.getPlayers()) {
                            if (isExempt(p)) continue;
                            if (p.getLocation().distanceSquared(zone) <= 2.25) { // 1.5 radius
                                p.damage(6.0); // 3 hearts
                                break; // Only damage once per tick
                            }
                        }
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new FlameEchoTrail(plugin); }
    }

    // =========================================================================
    // 72. PRE-DEATH ENVIRONMENTAL CHAOS -- random attacks every 3 seconds at 3% HP
    // (Design doc #72 -- Pre-Death Environmental Chaos)
    // =========================================================================
    public static class VoidEchoTrail extends EnvironmentalAttack {

        private final List<Location> trailZones = new ArrayList<>();
        private Location chargeStart;
        private Location chargeEnd;

        public VoidEchoTrail(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("void_echo_trail", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(180); // 9 seconds
            config.setCooldownTicks(300); // Triggers after void charge
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            // Straight charge path across arena
            double angle = Math.random() * 2 * Math.PI;
            chargeStart = center.clone().add(Math.cos(angle) * -15, 0, Math.sin(angle) * -15);
            chargeEnd = center.clone().add(Math.cos(angle) * 15, 0, Math.sin(angle) * 15);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || chargeStart == null || chargeEnd == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Trail placement: every 2 ticks for first 40 ticks
            if (ticksAlive <= 40 && ticksAlive % 2 == 0) {
                double t = ticksAlive / 40.0;
                Location zoneLoc = chargeStart.clone().add(
                        (chargeEnd.getX() - chargeStart.getX()) * t,
                        0.5,
                        (chargeEnd.getZ() - chargeStart.getZ()) * t
                );
                trailZones.add(zoneLoc);
                w.spawnParticle(Particle.DRAGON_BREATH, zoneLoc, 8, 0.5, 0.3, 0.5, 0.02);
            }

            // Active void zones: 5 dmg/sec for 6 seconds
            if (ticksAlive > 10 && ticksAlive <= 130) {
                // Particles
                if (ticksAlive % 6 == 0) {
                    for (Location zone : trailZones) {
                        w.spawnParticle(Particle.DRAGON_BREATH, zone, 4, 0.8, 0.3, 0.8, 0.01);
                    }
                }

                // Damage: 5 per second
                if (ticksAlive % 20 == 0) {
                    for (Location zone : trailZones) {
                        for (Player p : w.getPlayers()) {
                            if (isExempt(p)) continue;
                            if (p.getLocation().distanceSquared(zone) <= 4.0) { // 2 radius
                                p.damage(10.0); // 5 hearts
                                break;
                            }
                        }
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new VoidEchoTrail(plugin); }
    }

    // =========================================================================
    // 73. (Doc #75) CRYSTAL ECHO: AMETHYST SCATTER -- pillar fires shards radially
    // =========================================================================
    public static class CrystalEchoScatter extends EnvironmentalAttack {

        private Location pillarPos;
        private boolean shattered = false;

        public CrystalEchoScatter(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("crystal_echo_scatter", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(120); // 6 seconds
            config.setCooldownTicks(400); // Triggers on Dragon proximity
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            // Pillar near the spawn center
            double angle = Math.random() * 2 * Math.PI;
            pillarPos = center.clone().add(Math.cos(angle) * 12, 0, Math.sin(angle) * 12);

            // Warning: amethyst resonance
            DisplayBuilder.playSound(pillarPos, Sound.BLOCK_AMETHYST_CLUSTER_BREAK, 0.6f, 1.0f);
            w.spawnParticle(Particle.BLOCK, pillarPos.clone().add(0, 3, 0), 20, 0.5, 2, 0.5, 0,
                    Material.AMETHYST_BLOCK.createBlockData());
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || pillarPos == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Vibration warning: 20 ticks (1 second)
            if (ticksAlive <= 20) {
                if (ticksAlive % 5 == 0) {
                    w.spawnParticle(Particle.BLOCK, pillarPos.clone().add(0, 2, 0), 10, 0.5, 1.5, 0.5, 0,
                            Material.AMETHYST_BLOCK.createBlockData());
                }
                return;
            }

            // Fire shards in 8 directions
            if (!shattered) {
                shattered = true;

                DisplayBuilder.playSound(pillarPos, Sound.BLOCK_AMETHYST_CLUSTER_BREAK, 0.8f, 1.2f);
                w.spawnParticle(Particle.BLOCK, pillarPos, 60, 1, 2, 1, 0,
                        Material.AMETHYST_BLOCK.createBlockData());

                for (int dir = 0; dir < 8; dir++) {
                    double shardAngle = (2 * Math.PI * dir) / 8;
                    final double sa = shardAngle;

                    // Animate shard travel
                    for (int step = 0; step < 10; step++) {
                        final int s = step;
                        plugin.getServer().getScheduler().runTaskLater(plugin, () -> {
                            double dist = s + 1;
                            Location shardPos = pillarPos.clone().add(
                                    Math.cos(sa) * dist, 1.0, Math.sin(sa) * dist);
                            w.spawnParticle(Particle.BLOCK, shardPos, 6, 0.2, 0.2, 0.2, 0,
                                    Material.AMETHYST_BLOCK.createBlockData());
                            DisplayBuilder.playSound(shardPos, Sound.BLOCK_GLASS_BREAK, 0.3f, 0.8f);

                            // Damage at shard position
                            for (Player p : w.getPlayers()) {
                                if (isExempt(p)) continue;
                                if (p.getLocation().distanceSquared(shardPos) <= 4.0) { // 2 radius
                                    p.damage(10.0); // 5 hearts
                                }
                            }
                        }, step * 2L);
                    }
                }
            }

            // Aftermath: cracked pillar particles
            if (ticksAlive > 30 && ticksAlive <= 100 && ticksAlive % 10 == 0) {
                w.spawnParticle(Particle.BLOCK, pillarPos.clone().add(0, 1, 0), 5, 0.5, 1, 0.5, 0,
                        Material.AMETHYST_BLOCK.createBlockData());
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new CrystalEchoScatter(plugin); }
    }

    // =========================================================================
    // 74. (Doc #76) BRIMSTONE FOOTPRINT -- landing reaction zone
    // =========================================================================
    public static class BrimstoneFootprint extends EnvironmentalAttack {

        private final List<BlockDisplayHandle> craterHandles = new ArrayList<>();
        private Location landingPoint;
        private boolean erupted = false;
        private int eruptTick = -1;

        public BrimstoneFootprint(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("brimstone_footprint", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(200); // 10 seconds
            config.setCooldownTicks(300); // Triggers on Dragon landing
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            landingPoint = center.clone();

            // Swirling lava + flame at landing point
            w.spawnParticle(Particle.LAVA, landingPoint, 20, 1, 1, 1, 0);
            w.spawnParticle(Particle.FLAME, landingPoint.clone().add(0, 0.5, 0), 30, 2, 1, 2, 0.03);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || landingPoint == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Buildup: 40 ticks (2 seconds)
            if (ticksAlive <= 40) {
                if (ticksAlive % 5 == 0) {
                    w.spawnParticle(Particle.LAVA, landingPoint, 10, 1.5, 0.5, 1.5, 0);
                    w.spawnParticle(Particle.FLAME, landingPoint.clone().add(0, 0.5, 0), 15, 2, 0.5, 2, 0.02);
                }
                return;
            }

            // Eruption
            if (!erupted) {
                erupted = true;
                eruptTick = ticksAlive;

                DisplayBuilder.playSound(landingPoint, Sound.BLOCK_NETHERRACK_BREAK, 1.0f, 0.4f);
                DisplayBuilder.playSound(landingPoint, Sound.ENTITY_BLAZE_SHOOT, 0.6f, 0.5f);

                // Center burst
                w.spawnParticle(Particle.LAVA, landingPoint, 40, 2, 1, 2, 0);
                w.spawnParticle(Particle.FLAME, landingPoint, 60, 3, 2, 3, 0.05);

                // Entry damage: 8 in 8-block radius
                for (Player p : w.getPlayers()) {
                    if (isExempt(p)) continue;
                    if (p.getLocation().distanceSquared(landingPoint) <= 64.0) {
                        p.damage(16.0); // 8 hearts
                    }
                }

                // Crater displays
                for (int i = 0; i < 6; i++) {
                    double a = (2 * Math.PI * i) / 6;
                    Location cratLoc = landingPoint.clone().add(Math.cos(a) * 3, 0.05, Math.sin(a) * 3);
                    BlockDisplayHandle h = displayBuilder.spawnBlock(cratLoc, Material.MAGMA_BLOCK);
                    h.scale(1.5f, 0.15f, 1.5f).glow(200, 0, 50).interpolation(5, 0);
                    craterHandles.add(h);
                    spawnedEntities.add(h.entity());
                }

                // Three radial fire cracks
                for (int c = 0; c < 3; c++) {
                    double crackAngle = Math.random() * 2 * Math.PI;
                    for (int step = 0; step < 10; step++) {
                        Location crackPos = landingPoint.clone().add(
                                Math.cos(crackAngle) * (step + 1), 0.2,
                                Math.sin(crackAngle) * (step + 1));
                        w.spawnParticle(Particle.FLAME, crackPos, 3, 0.1, 0.3, 0.1, 0.01);
                    }
                }
            }

            // Ground fire: 3/sec for 6 seconds (120 ticks)
            if (eruptTick > 0 && ticksAlive - eruptTick <= 120) {
                if ((ticksAlive - eruptTick) % 4 == 0) {
                    w.spawnParticle(Particle.FLAME, landingPoint.clone().add(0, 0.3, 0), 10, 4, 0.3, 4, 0.01);
                }
                if ((ticksAlive - eruptTick) % 20 == 0) {
                    for (Player p : w.getPlayers()) {
                        if (isExempt(p)) continue;
                        if (p.getLocation().distanceSquared(landingPoint) <= 64.0) {
                            p.damage(6.0); // 3 hearts fire per second
                        }
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new BrimstoneFootprint(plugin); }
    }

    // =========================================================================
    // 75. (Doc #77) ORBIT TRAIL DENSITY -- persistent ring at Dragon orbit altitude
    // =========================================================================
    public static class OrbitTrailDensity extends EnvironmentalAttack {

        private double orbitRadius;

        public OrbitTrailDensity(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("orbit_trail_density", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(400); // 20 seconds
            config.setCooldownTicks(600); // After 3 orbits
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            orbitRadius = 14 + Math.random() * 6; // 14-20 blocks
            DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_AMBIENT, 0.2f, 0.5f);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null) return;
            World w = center.getWorld();
            if (w == null) return;

            double ringY = center.getY() + 12; // Y+12 above arena

            // Persistent ring particles
            if (ticksAlive % 4 == 0) {
                int points = 24;
                for (int i = 0; i < points; i++) {
                    double a = (2 * Math.PI * i) / points;
                    Location ringLoc = new Location(w,
                            center.getX() + Math.cos(a) * orbitRadius,
                            ringY,
                            center.getZ() + Math.sin(a) * orbitRadius);
                    w.spawnParticle(Particle.DRAGON_BREATH, ringLoc, 3, 0.3, 0.3, 0.3, 0.01);
                }
            }

            // Ambient sound
            if (ticksAlive % 40 == 0) {
                DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_AMBIENT, 0.15f, 0.5f);
            }

            // Damage: 4/sec for players on the ring path at that altitude
            if (ticksAlive % 20 == 0) {
                for (Player p : w.getPlayers()) {
                    if (isExempt(p)) continue;
                    Location pl = p.getLocation();
                    double hDist = Math.sqrt(Math.pow(pl.getX() - center.getX(), 2) + Math.pow(pl.getZ() - center.getZ(), 2));
                    if (Math.abs(hDist - orbitRadius) <= 2.0 && Math.abs(pl.getY() - ringY) <= 3.0) {
                        p.damage(8.0); // 4 hearts
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new OrbitTrailDensity(plugin); }
    }

    // =========================================================================
    // 76. (Doc #78) DIVE PATH SCAR -- low altitude purple line across arena
    // =========================================================================
    public static class DivePathScar extends EnvironmentalAttack {

        private Location scarStart;
        private Location scarEnd;

        public DivePathScar(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("dive_path_scar", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(200); // 10 seconds
            config.setCooldownTicks(300); // After each dive
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            double angle = Math.random() * 2 * Math.PI;
            scarStart = center.clone().add(Math.cos(angle) * -18, 0, Math.sin(angle) * -18);
            scarEnd = center.clone().add(Math.cos(angle) * 18, 0, Math.sin(angle) * 18);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || scarStart == null || scarEnd == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Persistent scar particles at Y+3 to Y+8
            if (ticksAlive % 5 == 0) {
                int linePoints = 20;
                for (int i = 0; i < linePoints; i++) {
                    double t = (double) i / linePoints;
                    double x = scarStart.getX() + (scarEnd.getX() - scarStart.getX()) * t;
                    double z = scarStart.getZ() + (scarEnd.getZ() - scarStart.getZ()) * t;
                    double y = center.getY() + 3 + Math.random() * 5;
                    w.spawnParticle(Particle.DRAGON_BREATH, new Location(w, x, y, z), 4, 0.5, 1, 0.5, 0.01);
                }
            }

            // Damage: 3/sec for players crossing the scar
            if (ticksAlive % 20 == 0) {
                for (Player p : w.getPlayers()) {
                    if (isExempt(p)) continue;
                    Location pl = p.getLocation();
                    // Distance to the scar line
                    double dist = distanceToLine(pl, scarStart, scarEnd);
                    if (dist <= 1.5 && pl.getY() >= center.getY() + 2 && pl.getY() <= center.getY() + 9) {
                        p.damage(6.0); // 3 hearts
                    }
                }
            }
        }

        private double distanceToLine(Location point, Location a, Location b) {
            double dx = b.getX() - a.getX();
            double dz = b.getZ() - a.getZ();
            double lenSq = dx * dx + dz * dz;
            if (lenSq == 0) return point.distance(a);
            double t = Math.max(0, Math.min(1, ((point.getX() - a.getX()) * dx + (point.getZ() - a.getZ()) * dz) / lenSq));
            double projX = a.getX() + t * dx;
            double projZ = a.getZ() + t * dz;
            return Math.sqrt(Math.pow(point.getX() - projX, 2) + Math.pow(point.getZ() - projZ, 2));
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new DivePathScar(plugin); }
    }

    // =========================================================================
    // 77. (Doc #79) CRYSTAL RESONANCE FIELD -- absorption field + shockwave
    // =========================================================================
    public static class CrystalResonanceField extends EnvironmentalAttack {

        private Location crystalPos;
        private boolean exploded = false;
        private int absorbStartTick = -1;

        public CrystalResonanceField(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("crystal_resonance_field", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(160); // 8 seconds
            config.setCooldownTicks(500); // On crystal charge
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            // Crystal position near arena edge
            double angle = Math.random() * 2 * Math.PI;
            crystalPos = center.clone().add(Math.cos(angle) * 14, 0, Math.sin(angle) * 14);
            absorbStartTick = 0;

            DisplayBuilder.playSound(crystalPos, Sound.BLOCK_AMETHYST_CLUSTER_BREAK, 0.6f, 0.5f);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null || crystalPos == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Absorption phase: 60 ticks (3 seconds)
            if (ticksAlive <= 60) {
                // END_ROD rising from crystal
                if (ticksAlive % 3 == 0) {
                    w.spawnParticle(Particle.END_ROD, crystalPos.clone().add(0, 2, 0), 10, 5, 5, 5, 0.02);

                    // Beam between crystal and dragon position (simulated upward)
                    Location beamTop = crystalPos.clone().add(0, 20, 0);
                    DisplayBuilder.particleLine(crystalPos, beamTop, Particle.END_ROD, 2, null);
                }

                // Sustained resonance sound
                if (ticksAlive % 20 == 0) {
                    DisplayBuilder.playSound(crystalPos, Sound.BLOCK_AMETHYST_CLUSTER_BREAK, 0.5f, 0.5f);
                }

                // Field damage: 6/sec within 10 blocks
                if (ticksAlive % 20 == 0) {
                    for (Player p : w.getPlayers()) {
                        if (isExempt(p)) continue;
                        if (p.getLocation().distanceSquared(crystalPos) <= 100.0) {
                            p.damage(12.0); // 6 hearts
                        }
                    }
                }
                return;
            }

            // Crystal explosion at tick 61
            if (!exploded) {
                exploded = true;

                DisplayBuilder.playSound(crystalPos, Sound.BLOCK_AMETHYST_CLUSTER_BREAK, 1.2f, 1.0f);

                // Explosion particles
                w.spawnParticle(Particle.BLOCK, crystalPos, 100, 2, 2, 2, 0,
                        Material.AMETHYST_BLOCK.createBlockData());
                w.spawnParticle(Particle.END_ROD, crystalPos, 80, 3, 3, 3, 0.1);

                // Shockwave: 12 damage + knockback within 8 blocks
                for (Player p : w.getPlayers()) {
                    if (isExempt(p)) continue;
                    if (p.getLocation().distanceSquared(crystalPos) <= 64.0) {
                        p.damage(12.0); // 6 hearts shockwave

                        // Knockback 5 blocks away from crystal
                        Vector knockback = p.getLocation().toVector().subtract(crystalPos.toVector()).normalize().multiply(1.5);
                        knockback.setY(0.4);
                        p.setVelocity(knockback);
                    }
                }

                // Expanding END_ROD ring
                for (double r = 1; r <= 8; r += 0.5) {
                    final double ringR = r;
                    plugin.getServer().getScheduler().runTaskLater(plugin, () ->
                            DisplayBuilder.particleRing(crystalPos.clone().add(0, 1, 0), ringR, Particle.END_ROD, 16, null),
                            (long) (r * 2));
                }
            }

            // Aftermath: rubble smoke
            int afterTick = ticksAlive - 61;
            if (afterTick > 0 && afterTick <= 80 && afterTick % 10 == 0) {
                w.spawnParticle(Particle.END_ROD, crystalPos.clone().add(0, 1, 0), 5, 1, 1, 1, 0.01);
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new CrystalResonanceField(plugin); }
    }

    // =========================================================================
    // 78. (Doc #80) DEEPENING VOID: ECHO ACCUMULATION -- all void zones triple density
    // =========================================================================
    public static class DeepVoidAccumulation extends EnvironmentalAttack {

        private boolean pulsed = false;

        public DeepVoidAccumulation(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("deep_void_accumulation", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(100); // 5 seconds
            config.setCooldownTicks(600); // After 5 void trails
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_GROWL, 1.0f, 0.4f);
            DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_AMBIENT, 0.8f, 0.3f);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // 4-second pulse: triple density on all existing void zones
            if (ticksAlive <= 80) {
                // Heavy DRAGON_BREATH across arena floor (simulating all zones at 3x)
                if (ticksAlive % 3 == 0) {
                    for (int i = 0; i < 10; i++) {
                        double angle = Math.random() * 2 * Math.PI;
                        double dist = Math.random() * 20;
                        Location zoneLoc = center.clone().add(Math.cos(angle) * dist, 0.5, Math.sin(angle) * dist);
                        w.spawnParticle(Particle.DRAGON_BREATH, zoneLoc, 5, 0.5, 0.3, 0.5, 0.01);
                    }
                }

                // Doubled scar damage: 6/sec for players in any zone area
                if (ticksAlive % 20 == 0 && !pulsed) {
                    for (Player p : w.getPlayers()) {
                        if (isExempt(p)) continue;
                        // Any player on the arena floor
                        if (p.getLocation().distanceSquared(center) <= 400) { // 20 block arena
                            p.damage(12.0); // 6 hearts doubled damage
                        }
                    }
                }

                // Crossing point burst at tick 40
                if (ticksAlive == 40 && !pulsed) {
                    pulsed = true;
                    w.spawnParticle(Particle.DRAGON_BREATH, center, 100, 3, 1, 3, 0.03);

                    // 25 burst at crossing points
                    for (Player p : w.getPlayers()) {
                        if (isExempt(p)) continue;
                        if (p.getLocation().distanceSquared(center) <= 16.0) {
                            p.damage(25.0); // 12.5 hearts burst
                        }
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new DeepVoidAccumulation(plugin); }
    }

    // =========================================================================
    // 79. (Doc #81) WING DOWNDRAFT ZONE -- push + damage below hovering Dragon
    // =========================================================================
    public static class WingDowndraftZone extends EnvironmentalAttack {

        public WingDowndraftZone(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("wing_downdraft_zone", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(200); // 10 seconds (while Dragon hovers)
            config.setCooldownTicks(300); // During hovering
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            // Immediate -- no warning
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // Smoke cyclone particles below Dragon
            if (ticksAlive % 3 == 0) {
                double angle = (ticksAlive * 0.2) % (2 * Math.PI);
                for (int i = 0; i < 6; i++) {
                    double a = angle + (2 * Math.PI * i) / 6;
                    double r = 3 + Math.random() * 7;
                    Location smokeLoc = center.clone().add(Math.cos(a) * r, Math.random() * 5, Math.sin(a) * r);
                    w.spawnParticle(Particle.SMOKE, smokeLoc, 4, 0.5, 0.5, 0.5, 0.03);
                }
            }

            // Push + damage every 30 ticks (1.5 seconds)
            if (ticksAlive % 30 == 0) {
                DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_FLAP, 0.4f, 0.8f);

                for (Player p : w.getPlayers()) {
                    if (isExempt(p)) continue;
                    if (p.getLocation().distanceSquared(center) <= 100.0) { // 10 radius
                        p.damage(8.0); // 4 hearts per push

                        // Push outward from center
                        Vector push = p.getLocation().toVector().subtract(center.toVector()).normalize().multiply(0.8);
                        push.setY(0.1);
                        p.setVelocity(push);
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new WingDowndraftZone(plugin); }
    }

    // =========================================================================
    // 80. (Doc #82) FULL ARENA ECHO SATURATION -- all zones pulse at 12% HP
    // =========================================================================
    public static class FullEchoSaturation extends EnvironmentalAttack {

        private boolean pulsed = false;

        public FullEchoSaturation(ChaosCraftPlugin plugin) {
            super(plugin, new AttackConfig("full_echo_saturation", AttackType.ENVIRONMENTAL, 4));
            config.setDamage(0.0);
            config.setDamageRadius(0.0);
            config.setDurationTicks(100); // 5 seconds
            config.setCooldownTicks(99999); // Scripted once at 12% HP
            config.setTicksBetweenDamage(999);
        }

        @Override
        protected void onSpawn(Location center) {
            World w = center.getWorld();
            if (w == null) return;

            DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_AMBIENT, 1.5f, 0.3f);
            DisplayBuilder.playSound(center, Sound.ENTITY_ENDER_DRAGON_GROWL, 1.0f, 0.4f);
            DisplayBuilder.playSound(center, Sound.BLOCK_ANCIENT_DEBRIS_BREAK, 0.8f, 0.3f);
        }

        @Override
        protected void onTick(int ticksAlive) {
            Location center = getCenter();
            if (center == null) return;
            World w = center.getWorld();
            if (w == null) return;

            // 20 ticks (1 second) ramp, then 60 tick (3 second) pulse
            if (ticksAlive <= 20) {
                if (ticksAlive % 4 == 0) {
                    // Intensifying particles across the arena
                    for (int i = 0; i < 15; i++) {
                        double angle = Math.random() * 2 * Math.PI;
                        double dist = Math.random() * 22;
                        Location zoneLoc = center.clone().add(Math.cos(angle) * dist, 0.3, Math.sin(angle) * dist);
                        w.spawnParticle(Particle.DRAGON_BREATH, zoneLoc, 5, 0.5, 0.5, 0.5, 0.01);
                    }
                }
                return;
            }

            // Full saturation pulse: 3 seconds at double density
            if (ticksAlive > 20 && ticksAlive <= 80) {
                if (ticksAlive % 2 == 0) {
                    for (int i = 0; i < 20; i++) {
                        double angle = Math.random() * 2 * Math.PI;
                        double dist = Math.random() * 22;
                        Location zoneLoc = center.clone().add(Math.cos(angle) * dist, 0.3 + Math.random() * 2, Math.sin(angle) * dist);
                        switch (i % 4) {
                            case 0 -> w.spawnParticle(Particle.DRAGON_BREATH, zoneLoc, 4, 0.5, 0.3, 0.5, 0.01);
                            case 1 -> w.spawnParticle(Particle.FLAME, zoneLoc, 3, 0.3, 0.3, 0.3, 0.01);
                            case 2 -> w.spawnParticle(Particle.END_ROD, zoneLoc, 3, 0.3, 0.3, 0.3, 0.01);
                            case 3 -> DisplayBuilder.dustParticles(zoneLoc, 3, 0.5, 128, 0, 255, 1.0f);
                        }
                    }

                    // Structural elements glowing
                    if (ticksAlive % 10 == 0) {
                        for (int s = 0; s < 6; s++) {
                            double a = (2 * Math.PI * s) / 6;
                            Location structLoc = center.clone().add(Math.cos(a) * 15, 3, Math.sin(a) * 15);
                            w.spawnParticle(Particle.TOTEM_OF_UNDYING, structLoc, 8, 1, 2, 1, 0.03);
                            w.spawnParticle(Particle.CRIT, structLoc, 5, 0.5, 1, 0.5, 0.1);
                        }
                    }
                }

                // Instant 8 damage to all players in any active zone
                if (!pulsed) {
                    pulsed = true;
                    for (Player p : w.getPlayers()) {
                        if (isExempt(p)) continue;
                        if (p.getLocation().distanceSquared(center) <= 484) { // 22 block arena radius
                            p.damage(16.0); // 8 hearts instant
                        }
                    }
                }
            }
        }

        @Override
        protected void onCleanup() { displayBuilder.removeAll(); }

        @Override
        public AbstractAttack newInstance() { return new FullEchoSaturation(plugin); }
    }
}
